### ISSUE TITLE
save word button

### ISSUE THREAD

**Issue by ksjogo** [cute-jumper/ace-flyspell#1]
Hello,
ace-flyspell is working great for me.
One possible improvement could be the addition of a key to save the word to be corrected to the user dictionary.

**Comment by cute-jumper** [comment]
Implemented in https://github.com/cute-jumper/ace-flyspell/commit/c94510b97a36375ab7b38ee519ceace9dc437189. You can use "," to insert the current word into the dictionary.

Just a quick hack and feedbacks are very welcome. Thanks!
