### ISSUE TITLE
Use Avy

### ISSUE THREAD

**Issue by noctuid** [cute-jumper/ace-flyspell#2]
It would be nice if this package used avy instead of ace-jump. From your [post here](https://www.reddit.com/r/emacs/comments/48afx9/add_multiple_cursors_using_ace_jump/d0ikfy4/) it sounds like you may have already done this locally?

**Comment by cute-jumper** [comment]
Thanks for reminding me of this! Yes, it has been done locally, but it is not quite polished for a release. I've added some other features as well. However, now it may be a good chance to finish the work. Hope I can get it done in a few days.

**Comment by noctuid** [comment]
Thanks!
