### ISSUE TITLE
Introduce variable to prevent being asked for confirmation when saving word in dictionary

### ISSUE THREAD

**Issue by publicimageltd** [cute-jumper/ace-flyspell#4]
Everytime I find a new word with `ace-flyspell` and want to save it to the dictionary, an annoying prompt asks me to confirm its saving. I want to mute that prompt. It seems that the function `ispell-pdict-save` is responsible for the prompt, and luckily, it offers an optional first parameter which mutes that prompt. So basically, the suggestion is to replace the following line in the definition of `ace-flyspell--insert-word`:

``
 (ispell-pdict-save)
``

with:

``
 (ispell-pdict-save ace-flyspell-confirm-new-words)
``

where the variable is defined as:

``
(defvar ace-flyspell-confirm-new-words t
  "Define whether to ask for confirmation when adding new words to the personal dictionary.")
``

**Comment by cute-jumper** [comment]
Thanks for the suggestion! The variable is called `ace-flyspell-new-word-no-query` with default value `nil`. You can set it to `t` to add new words without confirmation.
